apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sheetwise-gateway
spec:
  hosts:
    - "*"
  gateways:
    - sheetwise-ws-gateway
  http:
    - match:
        - uri:
            prefix: /ws
      route:
        - destination:
            host: backend-ws.default.svc.cluster.local
            port:
              number: 8080
