apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-nodejs-deployment
  labels:
    app: backend-nodejs
    version: v1

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend-nodejs
      version: v1

  template:
    metadata:
      labels:
        app: backend-nodejs
        version: v1

      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "false"

    spec:
      terminationGracePeriodSeconds: 30

      containers:
        - name: backend-nodejs-container
          image: sujalsharma/sheetwise-nodejs-backend:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          envFrom:
            - configMapRef:
                name: sheetwise-backend-config

            - secretRef:
                name: sheetwise-secrets

          volumeMounts:
            - name: sheetwise-nodejs-pv
              mountPath: /data/db

          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3

          startupProbe:
            httpGet:
              path: /api/health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 30

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

      volumes:
        - name: sheetwise-nodejs-pv
          persistentVolumeClaim:
            claimName: sheetwise-nodejs-pvc
