apiVersion: v1
kind: Service
metadata:
  name: backend-nodejs-service
  labels:
    app: auth-nodejs
    monitoring: sheetwise
spec:
  selector:
    app: backend-nodejs
  ports:
    - protocol: TCP
      name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
