apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-ws-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-ws
  template:
    metadata:
      labels:
        app: backend-ws
    spec:
      containers:
        - name: backend-ws-container
          image: sujalsharma/sheetwise-ws-backend:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: sheetwise-ws-config
            - secretRef:
                name: sheetwise-secrets