apiVersion: v1
kind: ConfigMap
metadata:
  name: sheetwise-backend-config
data:
  NODE: "Excel_Backend"
  DB_HOST: "postgres.default.svc.cluster.local"
  redis_host: "redis.default.svc.cluster.local"
  ELASTICSEARCH_URL: "44.223.91.24"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_USER: "postgres"
  NODE_ENV: "production"
  PORT: "3000"
  FRONTEND_URL: "https://sujalsharma.in"
  region: "us-east-1"
  model: "gemini-2.5-flash"
  embedding: "gemini-embedding-001"
  CHROMA_URL: "http://chromadb-service.chromadb.svc.cluster.local:8000"

