apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sheetwise-backend-route
spec:
  parentRefs:
    - name: sheetwise-gateway
  hostnames:
    - "example.com"  # <- change this
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: backend-nodejs-service
          port: 3000
