apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard" 
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard"  # "default" for Azure "standard" for GCP and "standard" for AWS
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sheetwise-nodejs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard"  # Match with PV
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sheetwise-ws-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard"  # Match with PV
  resources:
    requests:
      storage: 1Gi


