apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sheetwise-service-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - backend-nodejs
          - backend-ws

  namespaceSelector:
    matchNames:
      - default

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
